name: deepspot

channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python==3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - numpy
  - pandas
  - scipy
  - anndata
  - scanpy
  - squidpy
  - matplotlib
  - pyvips
  - scikit-learn
  - lightning
  
  - pip:
    - plotnine
    - ipykernel
    - huggingface_hub
    - transformers
    - timm
    - scikit-misc
    - torchmetrics
    - h5py
    - pyyaml
    - shapely
    - opencv-python
    - pillow
    - tqdm
    - hest
